=== Mohamedyousef44/XML-labs/lab-2/Employee.dtd
<?xml version="1.0" encoding="UTF-8"?>
<!ELEMENT employees (employee+)>

<!ELEMENT employee (name , email , phones , addresses)>

<!ELEMENT name (#PCDATA)>

<!ELEMENT email (#PCDATA)>

<!ELEMENT phones (phone+)>

<!ELEMENT phone (#PCDATA)>

<!ATTLIST phone type (mobile | work | home ) #IMPLIED>

<!ELEMENT addresses (address+)>

<!ELEMENT address (Street , BuildingNumber , Region , City ,country)>

<!ELEMENT Street (#PCDATA)>

<!ELEMENT BuildingNumber (#PCDATA)>

<!ELEMENT Region (#PCDATA)>

<!ELEMENT City (#PCDATA)>

<!ELEMENT country (#PCDATA)>

=== Mohamedyousef44/XML-labs/lab-2/Employee.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE employees SYSTEM "Employee.dtd">
<employees>

    <employee>

        <name>Mohamed Yossef</name>

        <email>2020.m@gmail.com</email>

        <phones>

            <phone type="mobile">01285287955</phone>
            <phone type="work">01285287955</phone>
            <phone type="home" >5342863</phone>

        </phones>

        <addresses>

            <address>

                <Street>66 st</Street>
                <BuildingNumber>84</BuildingNumber>
                <Region>sisdibeshr</Region>
                <City>Alexandria</City>
                <country>Egypt</country>
            
            </address>

        </addresses>

    </employee>
    <employee>

        <name>hossam abba</name>

        <email>2020.m@gmail.com</email>

        <phones>

            <phone type="mobile">01285287955</phone>
            <phone type="work">01285287955</phone>
            <phone type="home" >5342863</phone>

        </phones>

        <addresses>

            <address>

                <Street>66 st</Street>
                <BuildingNumber>84</BuildingNumber>
                <Region>sisdibeshr</Region>
                <City>Alexandria</City>
                <country>Egypt</country>
            
            </address>

        </addresses>

    </employee>
    <employee>

        <name>Ahmed slah</name>

        <email>2020.m@gmail.com</email>

        <phones>

            <phone type="mobile">01285287955</phone>
            <phone type="work">01285287955</phone>
            <phone type="home" >5342863</phone>

        </phones>

        <addresses>

            <address>

                <Street>66 st</Street>
                <BuildingNumber>84</BuildingNumber>
                <Region>sisdibeshr</Region>
                <City>Alexandria</City>
                <country>Egypt</country>
            
            </address>

        </addresses>

    </employee>

    
</employees>
